config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exams

  resources :patients

  resources :users

   root 'exams#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
    belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
     
     has_many :exams
     
     validates :name, presence: true
     validates :genre, presence: true
     validates :nip, presence: true
     
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true
  validates :lastname, presence: true
  validates :nip, presence: true
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :lastname, :nip, :email, :username, :password, :password_confirmation) 
    end
    devise_parameter_sanitizer.for(:account_update) do |u| 
      u.permit(:name, :lastname, :nip, :email, :username, :password, :password_confirmation, :current_password) 
    end
  end
  
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :index, :create, :edit, :update, :destroy]
  
  before_action :get_patients
  
  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.order("created_at DESC")
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :description, :publication, :patient_name, :state, :patient_id)
    end
    
    def get_patients
      @patients = Patient.order("name").map {|patient| [patient.name,patient.id]}
    end
    
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:nip, :name, :born, :genre)
      
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :publication %><br>
    <%= f.date_select :publication, :start_year => 1900 %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state %> (Pendiente o Realizado)
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.select :patient_id, options_for_select(@patients) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<h1>Listing exams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Publication</th>
      <th>State</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.name, exam %></td>
        <td><%= exam.publication %></td>
        <td>
          <%if(exam.state==true)%>
            <%='Realizado'%>
          <%else%>
            <%='Pendiente'%>
          <%end%>
        </td>
        <td><%= exam.patient.name %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path, class: 'button' %>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exam.description %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @exam.publication %>
</p>

<p>
  <strong>Patient name:</strong>
  <%= @exam.patient_name %>
</p>

<p>
  <strong>State:</strong>
    <%if(@exam.state==true)%>
      <%='Realizado'%>
    <%else%>
      <%='Pendiente'%>
    <%end%>
</p>

<p>
  <strong>Patient:</strong>
  <%= @exam.patient_id %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to 'Inicio', root_path %>
          </h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
    
      <section class="top-bar-section">
        
        <ul class="left">
          <li>
            <%= link_to 'Patients', patients_path %>
          </li>
        </ul>
        
        <ul class="right">
          <% if user_signed_in? %>
            <li class="active">
              <%= link_to current_user.name.upcase, edit_user_registration_path %>            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="active">
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Sign In', user_session_path %>
            </li>
          <% end %>
        </ul>
        
      </section>
    </nav>

    <% if flash[:notice] %>
      <div data-alert class="alert-box info radius">
        <%= flash[:notice] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div data-alert class="alert-box warning radius">
        <%= flash[:alert] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div data-alert class="alert-box alert radius">
        <%= flash[:error] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>


    <div class="row">
      <div class="columns large-12">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nip %><br>
    <%= f.number_field :nip %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :born %><br>
    <%= f.date_select :born, :start_year => 1900 %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.select :genre, options_for_select(['Masculino','Femenino']) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Nip</th>
      <th>Name</th>
      <th>Born</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.nip %></td>
        <td><%= patient.name %></td>
        <td><%= patient.born %></td>
        <td><%= patient.genre %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class: 'button' %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nip:</strong>
  <%= @patient.nip %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Born:</strong>
  <%= @patient.born %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @patient.genre %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>